version: '3.8'

services:
  mariadb:
    image: mysql:5.7
    command: --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foro
      MYSQL_USER: sumaxalex81
      MYSQL_PASSWORD: Jupiter1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  web:
    image: sumaxalex81/proyecto_docker:v1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mariadb_data: {}
